import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";

const rubik = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className + " min-h-screen"}>
        <div className="w-full p-4 bg-pink-500">
          <h3>User Role</h3>
        </div>
        <div className="p-6">{children}</div>
      </body>
    </html>
  );
}
